### ISSUE TITLE
タイトルを変更してください

### ISSUE THREAD

**Issue by Nishino0719** [hari0912/TestRepoRepo#2]
![image](https://user-images.githubusercontent.com/55534054/92043436-ff395680-edb6-11ea-9f30-0d18c0559223.png)

**Comment by hari0912** [comment]
h１をごきげんように変更しました

**Comment by Nishino0719** [comment]
プルリクエストを送ってください！
あと、変わったのをスクショとかで送ってくれると確認しやすいですー！

**Comment by hari0912** [comment]
送れてませんでした！

**Comment by Nishino0719** [comment]
#3 にて解決しました。確認してくださいっていうメッセージにしてください

**Comment by Nishino0719** [comment]
確認しました。
